name: Deploy Static Site to S3

on:
  push:
    branches:
      - main

permissions:              
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.5

    - name: Assume IAM Usage Role using OIDC
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::010438473890:role/usage-role
        aws-region: us-east-1

    - name: Initialize Terraform
      run: terraform init
      working-directory: terraform

    - name: Terraform Plan
      run: terraform plan
      working-directory: terraform
     
    - name: Assume IAM Deployment Role using OIDC
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::010438473890:role/deployment-role
        aws-region: us-east-1

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform
      
